

# This file was *autogenerated* from the file comparacion_generos.sage
from sage.all_cmdline import *   # import sage library

import sys
import os

# Cargar el visualizador
load('ribbongraph_visualizer.sage')

print("===========================================================")
print("   COMPARACIÓN DE GÉNEROS: BOUQUET DE 2 CÍRCULOS")
print("   Grafo: 1 vértice, 2 lazos")
print("===========================================================\n")

# Definición de aristas (fija para ambos casos)
# Arista A: semiaristas 1-2
# Arista B: semiaristas 3-4
rho = '(1,2)(3,4)'

# --- CASO 1: ESFERA ---
sigma1 = '(1,2,3,4)'
print(f"CASO 1: Orden Secuencial {sigma1}")
print(f"----------------------------------------")
viz1 = RibbonGraphVisualizer(sigma1, rho)
inv1 = viz1.invariantes()
print(f"Caras:  {inv1['caras_mu']}")
print(f"Género: {inv1['genus']}  <-- ESFERA")
print("\n")

# --- CASO 2: TORO ---
sigma2 = '(1,3,2,4)'
print(f"CASO 2: Orden Intercalado {sigma2}")
print(f"----------------------------------------")
viz2 = RibbonGraphVisualizer(sigma2, rho)
inv2 = viz2.invariantes()
print(f"Caras:  {inv2['caras_mu']}")
print(f"Género: {inv2['genus']}  <-- TORO")
print("\n")

print("CONCLUSIÓN:")
print("El mismo grafo abstracto genera superficies distintas según el orden cíclico (σ).")

