# -*- coding: utf-8 -*-
#!/usr/bin/env sage
"""
Quick Test - Prueba rápida de un ejemplo
==========================================
Genera los 5 pasos de un ribbon graph simple.
"""


# This file was *autogenerated* from the file quick_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_70 = Integer(70); _sage_const_1 = Integer(1)
load('ribbongraph_visualizer.sage')

print("\n" + "="*_sage_const_70 )
print("  RIBBON GRAPH - PRUEBA RÁPIDA")
print("="*_sage_const_70 )

# Crear ribbon graph simple
print("\n>>> Creando ribbon graph (Toro)...")
print("σ = (1,2,3)(4,5,6)")
print("ρ = (1,4)(2,5)(3,6)")

viz = crear_ribbon_simple()

# Mostrar invariantes
print("\n>>> Invariantes:")
inv = viz.invariantes()
for key, val in inv.items():
    print(f"  • {key:25s} = {val}")

# Generar secuencia completa
print("\n>>> Generando 5 pasos...")
archivos = viz.generar_secuencia_completa(
    output_dir='../outputs/imagenes',
    prefix='test_'
)

print("\n" + "="*_sage_const_70 )
print("  ✓ COMPLETADO")
print("="*_sage_const_70 )
print("\nArchivos generados:")
for i, f in enumerate(archivos, _sage_const_1 ):
    print(f"  {i}. {f}")

print("\n" + "="*_sage_const_70 )
print("Revisa las imágenes en: outputs/imagenes/test_paso*.png")
print("="*_sage_const_70  + "\n")

